version: 0.2
            
phases:
  install:
    commands:
      - echo Provisioning build server
      - apt-get update -f
      - apt-get install -f nodejs
  pre_build:
    commands:
      - echo Pulling app dependencies
      - npm install
  build:
    commands:
      - echo Building app
      - npm run build:prod
  post_build:
    commands:
      - Build completed
artifacts:
  files:
    - dist/**/*