version: 0.2
            
phases:
  install:
    commands:
      - echo Provisioning build server
      - sudo apt-get update && sudo apt-get -y upgrade
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y build-essential
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo Pulling app dependencies
      - npm install
  build:
    commands:
      - echo Building app
      - npm run build:prod
  post_build:
    commands:
      - Build completed
artifacts:
  files:
    - dist/**/*